trigger:
 branches:
   include:
     - main
pool: netflix-agent-pool

stages:
  - stage: 
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'netflix-svc'
              backendAzureRmOverrideSubscriptionID: '5b5ee99c-c2f3-49c3-935b-4db8f82d71a5'
              backendAzureRmResourceGroupName: 'rg-dev-01'
              backendAzureRmStorageAccountName: 'apexkastorage'
              backendAzureRmContainerName: 'bluedrum'
              backendAzureRmKey: 'netfix-key-statefile'